application: test-time-sheet
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:


- url: /CSS
  static_dir: CSS

- url: /jquery
  static_dir: jquery

- url: /image
  static_dir: image

- url: /FORM_DAILY_REPORTS_ADMIN_REPORT_ENTRY.do
  script: FORM_DAILY_REPORTS_ADMIN_REPORT_ENTRY.php

- url: /DB_MENU.do
  script: DB_MENU.php

- url: /COMMON.do
  script: COMMON.php

- url: /DB_DAILY_REPORTS_ADMIN_REPORT_ENTRY.do
  script: DB_DAILY_REPORTS_ADMIN_REPORT_ENTRY.php

- url: /FORM_DAILY_REPORTS_ADMIN_SEARCH_UPDATE_DELETE.do
  script: FORM_DAILY_REPORTS_ADMIN_SEARCH_UPDATE_DELETE.php

- url: /DB_DAILY_REPORTS_ADMIN_SEARCH_UPDATE_DELETE.do
  script: DB_DAILY_REPORTS_ADMIN_SEARCH_UPDATE_DELETE.php

- url: /FORM_ACCESS_RIGHTS_USER_SEARCH_DETAIL.do
  script: FORM_ACCESS_RIGHTS_USER_SEARCH_DETAIL.php

- url: /DB_ACCESS_RIGHTS_USER_SEARCH_DETAIL.do
  script: DB_ACCESS_RIGHTS_USER_SEARCH_DETAIL.php

- url: /FORM_ACCESS_RIGHTS_TERMINATE-SEARCH_UPDATE.do
  script: FORM_ACCESS_RIGHTS_TERMINATE-SEARCH_UPDATE.php

- url: /DB_ACCESS_RIGHTS_TERMINATE-SEARCH_UPDATE.do
  script: DB_ACCESS_RIGHTS_TERMINATE-SEARCH_UPDATE.php

- url: /ERROR_PAGE.do
  script: ERROR_PAGE.php

- url: /FORM_DAILY_REPORTS_USER_REPORT_ENTRY.do
  script: FORM_DAILY_REPORTS_USER_REPORT_ENTRY.php

- url: /DB_DAILY_REPORTS_USER_REPORT_ENTRY.do
  script: DB_DAILY_REPORTS_USER_REPORT_ENTRY.php

- url: /FORM_PROJECT_PROJECT_ENTRY_SEARCH_UPDATE.do
  script: FORM_PROJECT_PROJECT_ENTRY_SEARCH_UPDATE.php

- url: /DB_PROJECT_PROJECT_ENTRY_SEARCH_UPDATE.do
  script: DB_PROJECT_PROJECT_ENTRY_SEARCH_UPDATE.php

- url: /FORM_WEEKLY_REPORT_ADMIN_WEEKLY_SEARCH_UPDATE.do
  script: FORM_WEEKLY_REPORT_ADMIN_WEEKLY_SEARCH_UPDATE.php

- url: /FORM_WEEKLY_REPORT_ADMIN_WEEKLY_REPORT_ENTRY.do
  script: FORM_WEEKLY_REPORT_ADMIN_WEEKLY_REPORT_ENTRY.php

- url: /FORM_DAILY_REPORTS_USER_SEARCH_UPDATE.do
  script: FORM_DAILY_REPORTS_USER_SEARCH_UPDATE.php

- url: /DB_DAILY_REPORTS_USER_SEARCH_UPDATE.do
  script: DB_DAILY_REPORTS_USER_SEARCH_UPDATE.php

- url: /_ah/login_required
  script: do_openid_login.py

- url: /FORM_ACCESS_RIGHTS_ACCESS_RIGHTS-SEARCH_UPDATE.do
  script: FORM_ACCESS_RIGHTS_ACCESS_RIGHTS-SEARCH_UPDATE.php

- url: /DB_ACCESS_RIGHTS_ACCESS_RIGHTS-SEARCH_UPDATE.do
  script: DB_ACCESS_RIGHTS_ACCESS_RIGHTS-SEARCH_UPDATE.php

- url: /FORM_ACCESS_RIGHTS_SITE_MAINTENANCE.do
  script: FORM_ACCESS_RIGHTS_SITE_MAINTENANCE.php

- url: /DB_ACCESS_RIGHTS_SITE_MAINTENANCE.do
  script: DB_ACCESS_RIGHTS_SITE_MAINTENANCE.php

- url: /DB_REPORT_ATTENDANCE.do
  script: DB_REPORT_ATTENDANCE.php

- url: /FORM_REPORT_ATTENDANCE.do
  script: FORM_REPORT_ATTENDANCE.php

- url: /DB_EMPLOYEE_ENTRY.do
  script: DB_EMPLOYEE_ENTRY.php

- url: /FORM_EMPLOYEE_ENTRY.do
  script: FORM_EMPLOYEE_ENTRY.php

- url: /DB_EMPLOYEE_SEARCH_UPDATE.do
  script: DB_EMPLOYEE_SEARCH_UPDATE.php

- url: /FORM_EMPLOYEE_SEARCH_UPDATE.do
  script: FORM_EMPLOYEE_SEARCH_UPDATE.php

- url: /FORM_REPORT_REVENUE.do
  script: FORM_REPORT_REVENUE.php

- url: /DB_REPORT_REVENUE.do
  script: DB_REPORT_REVENUE.php

- url: /DB_REPORT_BANDWIDTH.do
  script: DB_REPORT_BANDWIDTH.php

- url: /FORM_REPORT_BANDWIDTH.do
  script: FORM_REPORT_BANDWIDTH.php

- url: /DB_EMAIL_EMAIL_TEMPLATE_ENTRY.do
  script: DB_EMAIL_EMAIL_TEMPLATE_ENTRY.php

- url: /DB_EMAIL_EMAIL_TEMPLATE_SEARCH_UPDATE.do
  script: DB_EMAIL_EMAIL_TEMPLATE_SEARCH_UPDATE.php

- url: /FORM_EMAIL_EMAIL_TEMPLATE_SEARCH_UPDATE.do
  script: FORM_EMAIL_EMAIL_TEMPLATE_SEARCH_UPDATE.php

- url: /FORM_EMAIL_EMAIL_TEMPLATE_ENTRY.do
  script: FORM_EMAIL_EMAIL_TEMPLATE_ENTRY.php


- url: /DB_WEEKLY_REPORT_ADMIN_WEEKLY_REPORT_ENTRY.do
  script: DB_WEEKLY_REPORT_ADMIN_WEEKLY_REPORT_ENTRY.php

- url: /DB_WEEKLY_REPORT_ADMIN_WEEKLY_SEARCH_UPDATE.do
  script: DB_WEEKLY_REPORT_ADMIN_WEEKLY_SEARCH_UPDATE.php


- url: /FORM_REPORT_DOOR_ACCESS.do
  script: FORM_REPORT_DOOR_ACCESS.php


- url: /DB_REPORT_DOOR_ACCESS.do
  script: DB_REPORT_DOOR_ACCESS.php


- url: /FORM_EMPLOYEE_COMPANY_PROPERTY_VERIFICATION.do
  script: FORM_EMPLOYEE_COMPANY_PROPERTY_VERIFICATION.php

- url: /DB_EMPLOYEE_COMPANY_PROPERTY_VERIFICATION.do
  script: DB_EMPLOYEE_COMPANY_PROPERTY_VERIFICATION.php

- url: /REMAINDER_MAIL
  script: REMAINDER_MAIL.php

- url: /ABSENT_MAIL
  script: ABSENT_MAIL.php

- url: /REPORT_MAIL_USER
  script: REPORT_MAIL_USER.php

- url: /REPORT_MAIL
  script: REPORT_MAIL.php

- url: /YESTERDAY_REPORT_MAIL
  script: YESTERDAY_REPORT_MAIL.php

- url: /DROP_TEMP_TABLE
  script: DROP_TEMP_TABLE.php

- url: /ATTENDANCE_REPORT_MAIL
  script: ATTENDANCE_REPORT_MAIL.php


- url: /REPORT_MAIL_ADMIN
  script: REPORT_MAIL_ADMIN.php

- url: /DB_REPORT_TICKLER_HISTORY.do
  script: DB_REPORT_TICKLER_HISTORY.php

- url: /FORM_REPORT_TICKLER_HISTORY.do
  script: FORM_REPORT_TICKLER_HISTORY.php



- url: /FORM_PUBLIC_HOLIDAY_ENTRY.do
  script: FORM_PUBLIC_HOLIDAY_ENTRY.php

- url: /DB_PUBLIC_HOLIDAY_ENTRY.do
  script: DB_PUBLIC_HOLIDAY_ENTRY.php



- url: .*
  script: MENU.php
  login: required


#- url: .*
#  script: ATTENDANCE_REPORT_MAIL_PDF.php





